---
# tasks file for sourcepoint
- name: Install SourcePoint
  ansible.builtin.git:
    repo: "https://github.com/Tylous/SourcePoint.git"
    dest: '{{ playbook_dir }}/tools/SourcePoint'
    version: main

- name: Source go env
  ansible.builtin.shell: source /etc/profile.d/golang.sh && go get gopkg.in/yaml.v2
  args:
    chdir: '{{ playbook_dir }}/tools/SourcePoint'
    creates: '{{ ansible_env.HOME }}/go/pkg/mod/cache/download/gopkg.in/yaml.v2'

- name: Build SourcePoint
  ansible.builtin.command: go build SourcePoint.go
  args:
    chdir: '{{ playbook_dir }}/tools/SourcePoint'
    creates: '{{ playbook_dir }}/tools/SourcePoint/SourcePoint'
