---
# tasks file for sourcepoint

- name: Install SourcePoint
  ansible.builtin.git:
    repo: "https://github.com/Tylous/SourcePoint.git"
    dest: '{{ playbook_dir }}/tools/SourcePoint'
    version: main
