---
# tasks file for sourcepoint
- name: Install git
  ansible.builtin.package:
    name: git
    state: present
    update_cache: yes

- name: Install SourcePoint
  ansible.builtin.git:
    repo: "https://github.com/Tylous/SourcePoint.git"
    dest: '{{ playbook_dir }}/tools/SourcePoint'
    version: main
