---
- name: Import upgrade playbook
  ansible.builtin.import_playbook: upgrade.yml

- name: Import python playbook
  ansible.builtin.import_playbook: python.yml

- name: Import extract playbook
  ansible.builtin.import_playbook: extract.yml
